!
! Copyright (C) 2024 Quantum ESPRESSO group
! This file is distributed under the terms of the
! GNU General Public License. See the file `License'
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!
!=======================================================================
MODULE elph_manager_generate
!=======================================================================
  !
  ! Generates the ph.x input file for Phase 2 (electron-phonon).
  !
  ! Strategy: read the original ph_input_file line by line and
  ! write a modified copy that:
  !   1. Sets  trans = .false.          (reuse saved dvscf)
  !   2. Sets  electron_phonon = '...'  (chosen elph mode)
  !   3. Inserts k-grid / smearing parameters if provided
  !   4. Strips any conflicting lines from the original input
  !
  ! The original ph_input_file is NOT modified.
  ! Output is written to 'ph_elph_auto.in'.
  !
  IMPLICIT NONE
  SAVE
  !
CONTAINS
  !
  !---------------------------------------------------------------------
  SUBROUTINE generate_elph_input(ph_elph_input_file)
  !---------------------------------------------------------------------
    !
    USE elph_manager_input, ONLY : ph_input_file, electron_phonon, &
                                   el_ph_nsigma, el_ph_sigma,       &
                                   verbose
    USE io_global,          ONLY : ionode, stdout
    !
    CHARACTER(LEN=256), INTENT(OUT) :: ph_elph_input_file
    !
    INTEGER            :: iunit_in, iunit_out, ios
    CHARACTER(LEN=512) :: line, line_up
    LOGICAL            :: in_namelist
    !
    ph_elph_input_file = 'ph_elph_auto.in'
    !
    IF (.NOT. ionode) RETURN
    !
    IF (verbose) THEN
       WRITE(*,'(/,5X,A)') REPEAT('-',50)
       WRITE(*,'(5X,A)')   '  Generating elph input: '//TRIM(ph_elph_input_file)
       WRITE(*,'(5X,A)')   REPEAT('-',50)
    END IF
    !
    iunit_in  = 20
    iunit_out = 21
    !
    OPEN(UNIT=iunit_in, FILE=TRIM(ph_input_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_elph_input', &
         'Cannot open ph_input_file: '//TRIM(ph_input_file), 1)
    !
    OPEN(UNIT=iunit_out, FILE=TRIM(ph_elph_input_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_elph_input', &
         'Cannot create: '//TRIM(ph_elph_input_file), 1)
    !
    ! Write header
    WRITE(iunit_out,'(A)') '! =============================================================='
    WRITE(iunit_out,'(A)') '! Auto-generated by elph_manager.x - DO NOT EDIT'
    WRITE(iunit_out,'(A)') '! Phase 2: Electron-phonon coupling coefficients'
    WRITE(iunit_out,'(A)') '! Uses dvscf saved in Phase 1 (trans=.false.)'
    WRITE(iunit_out,'(A)') '! =============================================================='
    !
    in_namelist = .FALSE.
    !
    DO
       READ(iunit_in, '(A)', IOSTAT=ios) line
       IF (ios /= 0) EXIT
       !
       ! Uppercase copy for case-insensitive keyword matching
       line_up = line
       CALL to_upper(line_up)
       !
       ! --- Detect start of &INPUTPH namelist ---
       IF (INDEX(TRIM(ADJUSTL(line_up)), '&INPUTPH') == 1) THEN
          in_namelist = .TRUE.
          WRITE(iunit_out,'(A)') TRIM(line)
          !
          ! Inject Phase 2 parameters immediately after opening namelist
          WRITE(iunit_out,'(A)') '  ! --- Injected by elph_manager.x ---'
          WRITE(iunit_out,'(A)') '  trans = .false.,'
          WRITE(iunit_out,'(2A)') "  electron_phonon = '", &
               TRIM(electron_phonon)//"',"
          !
          WRITE(iunit_out,'(A,I4,A)')   '  el_ph_nsigma = ', el_ph_nsigma, ','
          WRITE(iunit_out,'(A,F8.4,A)') '  el_ph_sigma  = ', el_ph_sigma,  ','
          WRITE(iunit_out,'(A)') '  ! --- End of injected parameters ---'
          !
          CYCLE
       END IF
       !
       ! --- Filter conflicting lines inside the namelist ---
       IF (in_namelist) THEN
          !
          ! Skip 'trans' (but not 'electron_phonon' which has no 'trans' substring issue)
          IF (is_keyword(line_up, 'TRANS') .AND. &
              INDEX(line_up, 'ELECTRON_PHONON') == 0) CYCLE
          !
          ! Skip electron_phonon (we set it above)
          IF (is_keyword(line_up, 'ELECTRON_PHONON')) CYCLE
          !
          ! Skip smearing params (we set them above)
          IF (is_keyword(line_up, 'EL_PH_NSIGMA')) CYCLE
          IF (is_keyword(line_up, 'EL_PH_SIGMA'))  CYCLE
          !
          ! Detect end of namelist
          IF (INDEX(TRIM(ADJUSTL(line_up)), '/') == 1 .OR. &
              INDEX(line_up, '&END') > 0) THEN
             in_namelist = .FALSE.
          END IF
          !
       END IF
       !
       WRITE(iunit_out,'(A)') TRIM(line)
       !
    END DO
    !
    CLOSE(iunit_in)
    CLOSE(iunit_out)
    !
    IF (verbose) THEN
       WRITE(*,'(5X,A)') 'Generated: '//TRIM(ph_elph_input_file)
       WRITE(*,'(5X,A)') 'Key parameters injected:'
       WRITE(*,'(7X,A)') 'trans           = .false.'
       WRITE(*,'(7X,2A)') "electron_phonon = '", TRIM(electron_phonon)//"'"
       WRITE(*,'(7X,A)') 'k-grid          = (from ph_input_file)'
    END IF
    !
  END SUBROUTINE generate_elph_input
  !
  !---------------------------------------------------------------------
  SUBROUTINE generate_single_q_input(iq, ph_single_file)
  !---------------------------------------------------------------------
    !
    ! Generate ph.x input for a single q-point (start_q = iq, last_q = iq).
    ! Used when ph_split_qpoints = .TRUE.
    !
    USE elph_manager_input, ONLY : ph_input_file, verbose
    USE io_global,          ONLY : ionode, stdout
    !
    INTEGER,            INTENT(IN)  :: iq
    CHARACTER(LEN=256), INTENT(OUT) :: ph_single_file
    !
    INTEGER            :: iunit_in, iunit_out, ios
    CHARACTER(LEN=512) :: line, line_up
    CHARACTER(LEN=8)   :: iq_str
    LOGICAL            :: in_namelist, injected
    !
    WRITE(iq_str, '(I4)') iq
    ph_single_file = 'ph_q'//TRIM(ADJUSTL(iq_str))//'.in'
    !
    IF (.NOT. ionode) RETURN
    !
    iunit_in  = 22
    iunit_out = 23
    !
    OPEN(UNIT=iunit_in, FILE=TRIM(ph_input_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_single_q_input', &
         'Cannot open ph_input_file: '//TRIM(ph_input_file), 1)
    !
    OPEN(UNIT=iunit_out, FILE=TRIM(ph_single_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_single_q_input', &
         'Cannot create: '//TRIM(ph_single_file), 1)
    !
    WRITE(iunit_out,'(A,I4,A)') '! q-point ', iq, &
         ' - auto-generated by elph_manager.x'
    !
    in_namelist = .FALSE.
    injected    = .FALSE.
    !
    DO
       READ(iunit_in, '(A)', IOSTAT=ios) line
       IF (ios /= 0) EXIT
       line_up = line
       CALL to_upper(line_up)
       !
       IF (INDEX(TRIM(ADJUSTL(line_up)), '&INPUTPH') == 1) THEN
          in_namelist = .TRUE.
          WRITE(iunit_out,'(A)') TRIM(line)
          WRITE(iunit_out,'(A,I4,A)') '  start_q = ', iq, ','
          WRITE(iunit_out,'(A,I4,A)') '  last_q  = ', iq, ','
          injected = .TRUE.
          CYCLE
       END IF
       !
       IF (in_namelist) THEN
          ! Skip any existing start_q or last_q lines
          IF (is_keyword(line_up, 'START_Q')) CYCLE
          IF (is_keyword(line_up, 'LAST_Q'))  CYCLE
          IF (INDEX(TRIM(ADJUSTL(line_up)), '/') == 1 .OR. &
              INDEX(line_up, '&END') > 0) THEN
             in_namelist = .FALSE.
          END IF
       END IF
       !
       WRITE(iunit_out,'(A)') TRIM(line)
    END DO
    !
    CLOSE(iunit_in)
    CLOSE(iunit_out)
    !
    IF (verbose) WRITE(*,'(5X,A,I4,A,A)') &
         'q-point ', iq, ' input: ', TRIM(ph_single_file)
    !
  END SUBROUTINE generate_single_q_input
  !
  !---------------------------------------------------------------------
  LOGICAL FUNCTION is_keyword(line, keyword)
  !---------------------------------------------------------------------
    !
    ! Returns .TRUE. if 'keyword' appears as an assignment target in 'line',
    ! i.e., the line contains 'keyword' followed (with optional spaces) by '='.
    ! This avoids false positives where a keyword appears in a comment.
    !
    CHARACTER(LEN=*), INTENT(IN) :: line, keyword
    !
    INTEGER :: pos, eq_pos
    CHARACTER(LEN=512) :: work
    !
    is_keyword = .FALSE.
    work = ADJUSTL(line)
    !
    ! Skip comment lines
    IF (work(1:1) == '!' .OR. work(1:1) == '#') RETURN
    !
    pos = INDEX(work, TRIM(keyword))
    IF (pos == 0) RETURN
    !
    ! Check that '=' follows after optional spaces
    eq_pos = INDEX(work(pos:), '=')
    IF (eq_pos == 0) RETURN
    !
    is_keyword = .TRUE.
    !
  END FUNCTION is_keyword
  !
  !---------------------------------------------------------------------
  SUBROUTINE to_upper(str)
  !---------------------------------------------------------------------
    !
    ! Converts string to uppercase in-place.
    !
    CHARACTER(LEN=*), INTENT(INOUT) :: str
    INTEGER :: i, n
    !
    n = LEN_TRIM(str)
    DO i = 1, n
       IF (str(i:i) >= 'a' .AND. str(i:i) <= 'z') THEN
          str(i:i) = CHAR(ICHAR(str(i:i)) - 32)
       END IF
    END DO
    !
  END SUBROUTINE to_upper
  !
END MODULE elph_manager_generate
