!
! Copyright (C) 2024 Quantum ESPRESSO group
! This file is distributed under the terms of the
! GNU General Public License. See the file `License'
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!
!=======================================================================
MODULE elph_manager_generate
!=======================================================================
  !
  ! Generates the ph.x input file for Phase 2 (electron-phonon).
  !
  ! Strategy: read the original ph_input_file line by line and
  ! write a modified copy that:
  !   1. Sets  trans = .false.          (reuse saved dvscf)
  !   2. Sets  electron_phonon = '...'  (chosen elph mode)
  !   3. Inserts k-grid / smearing parameters if provided
  !   4. Strips any conflicting lines from the original input
  !
  ! The original ph_input_file is NOT modified.
  ! Output is written to 'ph_elph_auto.in'.
  !
  IMPLICIT NONE
  SAVE
  !
CONTAINS
  !
  !---------------------------------------------------------------------
  SUBROUTINE generate_elph_input(ph_elph_input_file)
  !---------------------------------------------------------------------
    !
    USE elph_manager_input, ONLY : ph_input_file, electron_phonon, &
                                   el_ph_nsigma, el_ph_sigma,       &
                                   verbose
    USE io_global,          ONLY : ionode, stdout
    !
    CHARACTER(LEN=256), INTENT(OUT) :: ph_elph_input_file
    !
    INTEGER            :: iunit_in, iunit_out, ios
    CHARACTER(LEN=512) :: line, line_up
    LOGICAL            :: in_namelist
    !
    ph_elph_input_file = 'ph_elph_auto.in'
    !
    IF (.NOT. ionode) RETURN
    !
    IF (verbose) THEN
       WRITE(*,'(/,5X,A)') REPEAT('-',50)
       WRITE(*,'(5X,A)')   '  Generating elph input: '//TRIM(ph_elph_input_file)
       WRITE(*,'(5X,A)')   REPEAT('-',50)
    END IF
    !
    iunit_in  = 20
    iunit_out = 21
    !
    OPEN(UNIT=iunit_in, FILE=TRIM(ph_input_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_elph_input', &
         'Cannot open ph_input_file: '//TRIM(ph_input_file), 1)
    !
    OPEN(UNIT=iunit_out, FILE=TRIM(ph_elph_input_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_elph_input', &
         'Cannot create: '//TRIM(ph_elph_input_file), 1)
    !
    ! Write header
    WRITE(iunit_out,'(A)') '! =============================================================='
    WRITE(iunit_out,'(A)') '! Auto-generated by elph_manager.x - DO NOT EDIT'
    WRITE(iunit_out,'(A)') '! Phase 2: Electron-phonon coupling coefficients'
    WRITE(iunit_out,'(A)') '! Uses dvscf saved in Phase 1 (trans=.false.)'
    WRITE(iunit_out,'(A)') '! =============================================================='
    !
    in_namelist = .FALSE.
    !
    DO
       READ(iunit_in, '(A)', IOSTAT=ios) line
       IF (ios /= 0) EXIT
       !
       ! Uppercase copy for case-insensitive keyword matching
       line_up = line
       CALL to_upper(line_up)
       !
       ! --- Detect start of &INPUTPH namelist ---
       IF (INDEX(TRIM(ADJUSTL(line_up)), '&INPUTPH') == 1) THEN
          in_namelist = .TRUE.
          WRITE(iunit_out,'(A)') TRIM(line)
          !
          ! Inject Phase 2 parameters immediately after opening namelist
          WRITE(iunit_out,'(A)') '  ! --- Injected by elph_manager.x ---'
          WRITE(iunit_out,'(A)') '  trans = .false.,'
          WRITE(iunit_out,'(2A)') "  electron_phonon = '", &
               TRIM(electron_phonon)//"',"
          !
          WRITE(iunit_out,'(A,I4,A)')   '  el_ph_nsigma = ', el_ph_nsigma, ','
          WRITE(iunit_out,'(A,F8.4,A)') '  el_ph_sigma  = ', el_ph_sigma,  ','
          WRITE(iunit_out,'(A)') '  ! --- End of injected parameters ---'
          !
          CYCLE
       END IF
       !
       ! --- Filter conflicting lines inside the namelist ---
       IF (in_namelist) THEN
          !
          ! Skip 'trans' (but not 'electron_phonon' which has no 'trans' substring issue)
          IF (is_keyword(line_up, 'TRANS') .AND. &
              INDEX(line_up, 'ELECTRON_PHONON') == 0) CYCLE
          !
          ! Skip electron_phonon (we set it above)
          IF (is_keyword(line_up, 'ELECTRON_PHONON')) CYCLE
          !
          ! Skip smearing params (we set them above)
          IF (is_keyword(line_up, 'EL_PH_NSIGMA')) CYCLE
          IF (is_keyword(line_up, 'EL_PH_SIGMA'))  CYCLE
          !
          ! Detect end of namelist
          IF (INDEX(TRIM(ADJUSTL(line_up)), '/') == 1 .OR. &
              INDEX(line_up, '&END') > 0) THEN
             in_namelist = .FALSE.
          END IF
          !
       END IF
       !
       WRITE(iunit_out,'(A)') TRIM(line)
       !
    END DO
    !
    CLOSE(iunit_in)
    CLOSE(iunit_out)
    !
    IF (verbose) THEN
       WRITE(*,'(5X,A)') 'Generated: '//TRIM(ph_elph_input_file)
       WRITE(*,'(5X,A)') 'Key parameters injected:'
       WRITE(*,'(7X,A)') 'trans           = .false.'
       WRITE(*,'(7X,2A)') "electron_phonon = '", TRIM(electron_phonon)//"'"
       WRITE(*,'(7X,A)') 'k-grid          = (from ph_input_file)'
    END IF
    !
  END SUBROUTINE generate_elph_input
  !
  !---------------------------------------------------------------------
  SUBROUTINE generate_q2r_input(q2r_input_file)
  !---------------------------------------------------------------------
    !
    ! Generate q2r.x input to convert dyn matrices to force constants.
    ! q2r.x must be run before matdyn.x.
    !
    USE elph_manager_input, ONLY : ph_input_file, prefix, verbose
    USE io_global,          ONLY : ionode, stdout
    !
    CHARACTER(LEN=256), INTENT(OUT) :: q2r_input_file
    !
    INTEGER            :: iunit_ph, iunit_out, ios
    CHARACTER(LEN=512) :: line, line_up
    CHARACTER(LEN=256) :: fildyn_val
    INTEGER            :: nq1_val, nq2_val, nq3_val
    !
    q2r_input_file = 'q2r_auto.in'
    !
    IF (.NOT. ionode) RETURN
    !
    ! Parse fildyn and nq from ph_input_file
    fildyn_val = TRIM(prefix)//'.dyn'
    nq1_val = 2; nq2_val = 2; nq3_val = 2
    !
    iunit_ph = 33
    OPEN(UNIT=iunit_ph, FILE=TRIM(ph_input_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios == 0) THEN
       DO
          READ(iunit_ph, '(A)', IOSTAT=ios) line
          IF (ios /= 0) EXIT
          line_up = line
          CALL to_upper(line_up)
          IF (INDEX(line_up, 'FILDYN') > 0 .AND. INDEX(line_up, '=') > 0) THEN
             ios = INDEX(line, "'")
             IF (ios > 0) THEN
                fildyn_val = line(ios+1:)
                ios = INDEX(fildyn_val, "'")
                IF (ios > 0) fildyn_val = fildyn_val(1:ios-1)
             END IF
          END IF
          IF (INDEX(line_up, 'NQ1') > 0 .AND. INDEX(line_up, '=') > 0) &
             READ(line(INDEX(line_up,'NQ1')+4:), *, IOSTAT=ios) nq1_val
          IF (INDEX(line_up, 'NQ2') > 0 .AND. INDEX(line_up, '=') > 0) &
             READ(line(INDEX(line_up,'NQ2')+4:), *, IOSTAT=ios) nq2_val
          IF (INDEX(line_up, 'NQ3') > 0 .AND. INDEX(line_up, '=') > 0) &
             READ(line(INDEX(line_up,'NQ3')+4:), *, IOSTAT=ios) nq3_val
       END DO
       CLOSE(iunit_ph)
    END IF
    !
    iunit_out = 34
    OPEN(UNIT=iunit_out, FILE=TRIM(q2r_input_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_q2r_input', &
         'Cannot create: '//TRIM(q2r_input_file), 1)
    !
    WRITE(iunit_out,'(A)') '! Auto-generated by elph_manager.x'
    WRITE(iunit_out,'(A)') '&INPUT'
    WRITE(iunit_out,'(3A)') "  fildyn = '", TRIM(fildyn_val), "',"
    WRITE(iunit_out,'(3A)') "  flfrc  = '", TRIM(fildyn_val), ".fc',"
    WRITE(iunit_out,'(A)') "  zasr    = 'simple',"
    WRITE(iunit_out,'(A)') '/'
    CLOSE(iunit_out)
    !
    IF (verbose) WRITE(stdout,'(5X,A)') &
         'Generated q2r input: '//TRIM(q2r_input_file)
    !
  END SUBROUTINE generate_q2r_input
  !
  !---------------------------------------------------------------------
  SUBROUTINE generate_matdyn_input(matdyn_input_file)
  !---------------------------------------------------------------------
    !
    ! Generate matdyn.x input for phonon dispersion.
    ! Reads fildyn and q-grid from ph_input_file.
    ! Reads q-path from matdyn_qpath_file.
    !
    USE elph_manager_input, ONLY : ph_input_file, prefix, outdir, &
                                   matdyn_qpath_file, verbose
    USE io_global,          ONLY : ionode, stdout
    !
    CHARACTER(LEN=256), INTENT(OUT) :: matdyn_input_file
    !
    INTEGER            :: iunit_ph, iunit_out, iunit_path, ios
    CHARACTER(LEN=512) :: line, line_up
    CHARACTER(LEN=256) :: fildyn_val
    INTEGER            :: nq1_val, nq2_val, nq3_val
    LOGICAL            :: found_fildyn, found_nq
    !
    matdyn_input_file = 'matdyn_auto.in'
    !
    IF (.NOT. ionode) RETURN
    !
    IF (LEN_TRIM(matdyn_qpath_file) == 0) &
       CALL errore('generate_matdyn_input', &
       'matdyn_qpath_file must be set when compute_matdyn = .true.', 1)
    !
    ! --- Parse ph_input_file for fildyn and nq ---
    fildyn_val = TRIM(prefix)//'.dyn'
    nq1_val = 2; nq2_val = 2; nq3_val = 2
    found_fildyn = .FALSE.; found_nq = .FALSE.
    !
    iunit_ph = 30
    OPEN(UNIT=iunit_ph, FILE=TRIM(ph_input_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios == 0) THEN
       DO
          READ(iunit_ph, '(A)', IOSTAT=ios) line
          IF (ios /= 0) EXIT
          line_up = line
          CALL to_upper(line_up)
          IF (INDEX(line_up, 'FILDYN') > 0 .AND. INDEX(line_up, '=') > 0) THEN
             ! Extract value between quotes
             ios = INDEX(line, "'")
             IF (ios > 0) THEN
                fildyn_val = line(ios+1:)
                ios = INDEX(fildyn_val, "'")
                IF (ios > 0) fildyn_val = fildyn_val(1:ios-1)
                found_fildyn = .TRUE.
             END IF
          END IF
          IF (INDEX(line_up, 'NQ1') > 0 .AND. INDEX(line_up, '=') > 0) THEN
             READ(line(INDEX(line_up,'NQ1')+4:), *, IOSTAT=ios) nq1_val
             found_nq = .TRUE.
          END IF
          IF (INDEX(line_up, 'NQ2') > 0 .AND. INDEX(line_up, '=') > 0) THEN
             READ(line(INDEX(line_up,'NQ2')+4:), *, IOSTAT=ios) nq2_val
          END IF
          IF (INDEX(line_up, 'NQ3') > 0 .AND. INDEX(line_up, '=') > 0) THEN
             READ(line(INDEX(line_up,'NQ3')+4:), *, IOSTAT=ios) nq3_val
          END IF
       END DO
       CLOSE(iunit_ph)
    END IF
    !
    ! --- Write matdyn.x input ---
    iunit_out = 31
    OPEN(UNIT=iunit_out, FILE=TRIM(matdyn_input_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_matdyn_input', &
         'Cannot create: '//TRIM(matdyn_input_file), 1)
    !
    WRITE(iunit_out,'(A)') '! Auto-generated by elph_manager.x'
    WRITE(iunit_out,'(A)') '&INPUT'
    WRITE(iunit_out,'(3A)') "  flfrc   = '", TRIM(fildyn_val), ".fc',"
    WRITE(iunit_out,'(A)') "  flfrq   = 'matdyn.freq',"
    WRITE(iunit_out,'(A)') "  flvec   = 'matdyn.modes',"
    WRITE(iunit_out,'(A)') "  dos     = .false.,"
    WRITE(iunit_out,'(A)') "  asr              = 'simple',"
    WRITE(iunit_out,'(A)') "  q_in_band_form   = .true.,"
    WRITE(iunit_out,'(A)') '/'
    !
    ! Append q-path from matdyn_qpath_file
    iunit_path = 32
    OPEN(UNIT=iunit_path, FILE=TRIM(matdyn_qpath_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_matdyn_input', &
         'Cannot open matdyn_qpath_file: '//TRIM(matdyn_qpath_file), 1)
    DO
       READ(iunit_path, '(A)', IOSTAT=ios) line
       IF (ios /= 0) EXIT
       WRITE(iunit_out,'(A)') TRIM(line)
    END DO
    CLOSE(iunit_path)
    CLOSE(iunit_out)
    !
    IF (verbose) WRITE(stdout,'(5X,A)') &
         'Generated matdyn input: '//TRIM(matdyn_input_file)
    !
  END SUBROUTINE generate_matdyn_input
  !
  !---------------------------------------------------------------------
  SUBROUTINE generate_bands_input(pw_bands_file, bandspp_file)
  !---------------------------------------------------------------------
    !
    ! Generate pw.x input for band structure calculation.
    ! Reads structural parameters from scf_input_file.
    ! Replaces calculation='scf' with calculation='bands'.
    ! Appends K_POINTS from bands_kpath_file.
    !
    USE elph_manager_input, ONLY : pw_input_file, prefix, outdir, &
                                   bands_kpath_file, verbose
    USE io_global,          ONLY : ionode, stdout
    !
    CHARACTER(LEN=256), INTENT(OUT) :: pw_bands_file, bandspp_file
    !
    INTEGER            :: iunit_in, iunit_out, iunit_kpath, ios
    CHARACTER(LEN=512) :: line, line_up
    LOGICAL            :: in_kpoints
    !
    pw_bands_file = 'pw_bands_auto.in'
    bandspp_file  = 'bandspp_auto.in'
    !
    IF (.NOT. ionode) RETURN
    !
    IF (LEN_TRIM(bands_kpath_file) == 0) &
       CALL errore('generate_bands_input', &
       'bands_kpath_file must be set when compute_bands = .true.', 1)
    !
    ! --- Generate pw.x bands input ---
    iunit_in  = 35
    iunit_out = 36
    !
    OPEN(UNIT=iunit_in, FILE=TRIM(pw_input_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_bands_input', &
         'Cannot open pw_input_file: '//TRIM(pw_input_file), 1)
    !
    OPEN(UNIT=iunit_out, FILE=TRIM(pw_bands_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_bands_input', &
         'Cannot create: '//TRIM(pw_bands_file), 1)
    !
    WRITE(iunit_out,'(A)') '! Auto-generated by elph_manager.x (bands)'
    !
    in_kpoints = .FALSE.
    DO
       READ(iunit_in, '(A)', IOSTAT=ios) line
       IF (ios /= 0) EXIT
       line_up = line
       CALL to_upper(line_up)
       !
       ! Replace calculation = 'scf' with 'bands'
       IF (is_keyword(line_up, 'CALCULATION')) THEN
          WRITE(iunit_out,'(A)') "  calculation = 'bands',"
          CYCLE
       END IF
       !
       ! Skip original K_POINTS card (we replace it with the path)
       IF (INDEX(TRIM(ADJUSTL(line_up)), 'K_POINTS') == 1) THEN
          in_kpoints = .TRUE.
          CYCLE
       END IF
       IF (in_kpoints) THEN
          ! Skip one line of K_POINTS data, then stop skipping
          in_kpoints = .FALSE.
          CYCLE
       END IF
       !
       WRITE(iunit_out,'(A)') TRIM(line)
    END DO
    CLOSE(iunit_in)
    !
    ! Append crystal_b k-path
    WRITE(iunit_out,'(A)') 'K_POINTS crystal_b'
    iunit_kpath = 37
    OPEN(UNIT=iunit_kpath, FILE=TRIM(bands_kpath_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_bands_input', &
         'Cannot open bands_kpath_file: '//TRIM(bands_kpath_file), 1)
    DO
       READ(iunit_kpath, '(A)', IOSTAT=ios) line
       IF (ios /= 0) EXIT
       WRITE(iunit_out,'(A)') TRIM(line)
    END DO
    CLOSE(iunit_kpath)
    CLOSE(iunit_out)
    !
    ! --- Generate bands.x post-processing input ---
    iunit_out = 38
    OPEN(UNIT=iunit_out, FILE=TRIM(bandspp_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_bands_input', &
         'Cannot create: '//TRIM(bandspp_file), 1)
    !
    WRITE(iunit_out,'(A)') '! Auto-generated by elph_manager.x (bands.x pp)'
    WRITE(iunit_out,'(A)') '&BANDS'
    WRITE(iunit_out,'(3A)') "  prefix  = '", TRIM(prefix), "',"
    WRITE(iunit_out,'(3A)') "  outdir  = '", TRIM(outdir), "',"
    WRITE(iunit_out,'(3A)') "  filband = '", TRIM(prefix), ".bands.dat',"
    WRITE(iunit_out,'(A)') '/'
    CLOSE(iunit_out)
    !
    IF (verbose) THEN
       WRITE(stdout,'(5X,A)') 'Generated bands input: '//TRIM(pw_bands_file)
       WRITE(stdout,'(5X,A)') 'Generated bandspp input: '//TRIM(bandspp_file)
    END IF
    !
  END SUBROUTINE generate_bands_input
  !
  !---------------------------------------------------------------------
  SUBROUTINE generate_single_q_input(iq, ph_single_file)
  !---------------------------------------------------------------------
    !
    ! Generate ph.x input for a single q-point (start_q = iq, last_q = iq).
    ! Used when ph_split_qpoints = .TRUE.
    !
    USE elph_manager_input, ONLY : ph_input_file, verbose
    USE io_global,          ONLY : ionode, stdout
    !
    INTEGER,            INTENT(IN)  :: iq
    CHARACTER(LEN=256), INTENT(OUT) :: ph_single_file
    !
    INTEGER            :: iunit_in, iunit_out, ios
    CHARACTER(LEN=512) :: line, line_up
    CHARACTER(LEN=8)   :: iq_str
    LOGICAL            :: in_namelist, injected
    !
    WRITE(iq_str, '(I4)') iq
    ph_single_file = 'ph_q'//TRIM(ADJUSTL(iq_str))//'.in'
    !
    IF (.NOT. ionode) RETURN
    !
    iunit_in  = 22
    iunit_out = 23
    !
    OPEN(UNIT=iunit_in, FILE=TRIM(ph_input_file), STATUS='OLD', &
         ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_single_q_input', &
         'Cannot open ph_input_file: '//TRIM(ph_input_file), 1)
    !
    OPEN(UNIT=iunit_out, FILE=TRIM(ph_single_file), &
         STATUS='REPLACE', ACTION='WRITE', IOSTAT=ios)
    IF (ios /= 0) CALL errore('generate_single_q_input', &
         'Cannot create: '//TRIM(ph_single_file), 1)
    !
    WRITE(iunit_out,'(A,I4,A)') '! q-point ', iq, &
         ' - auto-generated by elph_manager.x'
    !
    in_namelist = .FALSE.
    injected    = .FALSE.
    !
    DO
       READ(iunit_in, '(A)', IOSTAT=ios) line
       IF (ios /= 0) EXIT
       line_up = line
       CALL to_upper(line_up)
       !
       IF (INDEX(TRIM(ADJUSTL(line_up)), '&INPUTPH') == 1) THEN
          in_namelist = .TRUE.
          WRITE(iunit_out,'(A)') TRIM(line)
          WRITE(iunit_out,'(A,I4,A)') '  start_q = ', iq, ','
          WRITE(iunit_out,'(A,I4,A)') '  last_q  = ', iq, ','
          injected = .TRUE.
          CYCLE
       END IF
       !
       IF (in_namelist) THEN
          ! Skip any existing start_q or last_q lines
          IF (is_keyword(line_up, 'START_Q')) CYCLE
          IF (is_keyword(line_up, 'LAST_Q'))  CYCLE
          IF (INDEX(TRIM(ADJUSTL(line_up)), '/') == 1 .OR. &
              INDEX(line_up, '&END') > 0) THEN
             in_namelist = .FALSE.
          END IF
       END IF
       !
       WRITE(iunit_out,'(A)') TRIM(line)
    END DO
    !
    CLOSE(iunit_in)
    CLOSE(iunit_out)
    !
    IF (verbose) WRITE(*,'(5X,A,I4,A,A)') &
         'q-point ', iq, ' input: ', TRIM(ph_single_file)
    !
  END SUBROUTINE generate_single_q_input
  !
  !---------------------------------------------------------------------
  LOGICAL FUNCTION is_keyword(line, keyword)
  !---------------------------------------------------------------------
    !
    ! Returns .TRUE. if 'keyword' appears as an assignment target in 'line',
    ! i.e., the line contains 'keyword' followed (with optional spaces) by '='.
    ! This avoids false positives where a keyword appears in a comment.
    !
    CHARACTER(LEN=*), INTENT(IN) :: line, keyword
    !
    INTEGER :: pos, eq_pos
    CHARACTER(LEN=512) :: work
    !
    is_keyword = .FALSE.
    work = ADJUSTL(line)
    !
    ! Skip comment lines
    IF (work(1:1) == '!' .OR. work(1:1) == '#') RETURN
    !
    pos = INDEX(work, TRIM(keyword))
    IF (pos == 0) RETURN
    !
    ! Check that '=' follows after optional spaces
    eq_pos = INDEX(work(pos:), '=')
    IF (eq_pos == 0) RETURN
    !
    is_keyword = .TRUE.
    !
  END FUNCTION is_keyword
  !
  !---------------------------------------------------------------------
  SUBROUTINE to_upper(str)
  !---------------------------------------------------------------------
    !
    ! Converts string to uppercase in-place.
    !
    CHARACTER(LEN=*), INTENT(INOUT) :: str
    INTEGER :: i, n
    !
    n = LEN_TRIM(str)
    DO i = 1, n
       IF (str(i:i) >= 'a' .AND. str(i:i) <= 'z') THEN
          str(i:i) = CHAR(ICHAR(str(i:i)) - 32)
       END IF
    END DO
    !
  END SUBROUTINE to_upper
  !
END MODULE elph_manager_generate
